version: '2'

services:
  jiradb:
    image: postgres:9.4
    container_name: ${DC_PREFIX}_jiradb
    ports:
      - "${DC_DB_PORT}:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${DC_DB_PW}
    networks:
      - jira_network

#
# JIRA itself
#
# if you mount installation directory, /opt/atlassian, harder to update jira version
# Default JIRA application home directory = /var/atlassian/jira
#
  jira7:
    image: cptactionhank/atlassian-jira-software:7.5.0
    container_name: ${DC_PREFIX}_jira7
    ports:
      - "${DC_JIRA_PORT}:8080"
    volumes:
      - ./jira-home:/var/atlassian/jira
      - /etc/timezone:/etc/timezone:ro
    environment:
      - X_PROXY_NAME=${DC_JIRA_NAME}
      - X_PROXY_PORT=443
      - X_PROXY_SCHEME=https
    depends_on:
      - jiradb
    networks:
      - jira_network
#
# Bitbucket
#
  bitbucket5:
    image: atlassian/bitbucket-server:5.2
    container_name: ${DC_PREFIX}_bitbucket5
    ports:
      - "${DC_BITBUCKET_PORT}:7990"
      - "${DC_SSH_PORT}:7999"
    volumes:
      - ./bitbucket-home:/var/atlassian/application-data/bitbucket
      - /etc/timezone:/etc/timezone:ro
    environment:
      - SERVER_PROXY_NAME=${DC_BITBUCKET_NAME}
      - SERVER_PROXY_PORT=443
      - SERVER_SCHEME=https
      - SERVER_SECURE=true
    depends_on:
      - jira7
    networks:
      - jira_network
networks:
  jira_network:

